### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by miguelkix30** [AlexAltea/orbital#83]
I have an error building with CMake ..

```
CMake Error at CMakeLists.txt:59 (include):
  include could not find requested file:

    C:/Users/Miguel/Desktop/orbital/externals/core.cmake


-- Configuring incomplete, errors occurred!
```

**Comment by AlexAltea** [comment]
A dependency for Orbital (`core.h`, `core.cmake`) is not publicly available at the moment, thus Orbital cannot be built.

I've still decided to publish the source code, because:
1. It serves as documentation for both PS4 hardware and software.
2. Anybody who is interested enough in making Orbital build, can create a QEMU-shim to try out my code (e.g. forwarding *core.h* class methods such as `PCIDevice::register_bar` to QEMU's `pci_register_bar`). Annoying and non-trivial but would work.
